package com.yizhao;

public enum StatesOfServer {
	STATE_PER_PACKAGE_UPSERT, STATE_PER_PACKAGE_GET, STATE_PER_PACKAGE_DELETE,
	STATE_PER_PACKAGE_AND_USER_UPSERT, STATE_PER_PACKAGE_AND_USER_GET, STATE_PER_PACKAGE_AND_USER_DELETE
}

